apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
namespace: cackalacky
images:
- name: 059039070213.dkr.ecr.us-east-1.amazonaws.com/cackalacky-hive
  newName: 059039070213.dkr.ecr.us-east-1.amazonaws.com/cackalacky-hive
  newTag: master-42e5d329870bdc7338189120a5509d41cfb9f317
